print("列表的正索引，从左到右边，0开始")
print("列表的负数索引，从右到左，-1开始，-1，-2，-3")

list=[1,2,3,4,5,6,7,8,9]
print(list[0])
print(list[1])
print(list[2])
print(list[3])
print(list[4])
print(list[5])
print(list[6])
print(list[7])
print(list[8])
print("负索引")
print(list[-1])
print(list[-2])
print(list[-3])
print(list[-4])
print(list[-5])
print(list[-6])
print(list[-7])
print(list[-8])
print(list[-9])

print("索引不可以超过原数的长度 报错：IndexError: list index out of range")
print(list[10])